set timeout 5
set port [lindex $argv 0]
set filename [lindex $argv 1]
set expected_msg_text [lindex $argv 2] 

log_user 0

proc print_res {input expected actual status} {
    puts "   INPUT    : $input"
    puts "   EXPECTED : $expected"
    puts "   ACTUAL   : $actual"
    if {$status == "PASS"} {
        puts "   RESULT   : \033\[1;32m\[PASS\]\033\[0m"
    } else {
        puts "   RESULT   : \033\[1;31m\[FAIL\]\033\[0m"
    }
}

spawn ./client 127.0.0.1 tcp $port
expect "> "
send "load $filename\r"

expect {
    # Ловим любые варианты сообщений об ошибках
    -re "Неверное.*|Ошибка.*|Некорректн.*" {
        set received $expect_out(0,string)
        print_res "load $filename" "$expected_msg_text" "$received" "PASS"
        exit 0
    }
    "Граф успешно загружен" {
        print_res "load $filename" "$expected_msg_text" "Граф успешно загружен (ОШИБКА НЕ ПОЙМАНА)" "FAIL"
        exit 1
    }
    timeout {
        print_res "load $filename" "$expected_msg_text" "TIMEOUT" "FAIL"
        exit 1
    }
}
