set timeout 10
set protocol [lindex $argv 0]
set port [lindex $argv 1]
set filename [lindex $argv 2]
set cmd_input "load $filename"
set expected_msg "Граф успешно загружен"

log_user 0 ;# Скрываем лишний шум

spawn ./client 127.0.0.1 $protocol $port
expect "> "
send "$cmd_input\r"

puts "Ввод:             $cmd_input"
puts "Ожидаемый вывод:  $expected_msg"

expect {
    -re "Граф успешно загружен" {
        # Получаем строку из буфера для вывода
        puts "Фактический вывод: Граф успешно загружен"
        # Проверяем query для надежности
        expect "> "
        send "query 0 1\r"
        expect {
            "Длина пути 2" # PASS
            timeout { puts "Фактический вывод (Query): Timeout"; exit 1 }
        }
    }
    timeout {
        set output $expect_out(buffer)
        # Очищаем вывод от мусора (символы новой строки) для красоты
        regsub -all {\n} $output " " output
        puts "Фактический вывод: (TIMEOUT) $output"
        exit 1
    }
    -re "Ошибка.*" {
        set output $expect_out(buffer)
        puts "Фактический вывод: $output"
        exit 1
    }
}